In [1]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
n_inputs = 3
n_neurons = 5

In [3]:
X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

In [4]:
Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons], dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons], dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

In [5]:
Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

In [6]:
# input data (mini-batch)
# t = 0

X0_batch = np.array([[0, 1, 2], # sample 0 
                     [3, 4, 5], # sample 1 
                     [6, 7, 8], # sample 2 
                     [9, 0, 1]]) # sample 3 
# t = 1 
X1_batch = np.array([[9, 8, 7], 
                     [3, 4, 5], 
                     [6, 5, 4], 
                     [3, 2, 1]])

In [7]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict= {X0: X0_batch, X1: X1_batch})

In [8]:
print('Y0_val:{}\n{}'.format(Y0_val.shape, Y0_val))

Y0_val:(4, 5)
[[-0.55799633 -0.99968463  0.68298274  0.99870634 -0.36427596]
 [-0.97503287 -0.999488    0.31821194  1.         -0.98223263]
 [-0.9988742  -0.99916875 -0.1735947   1.         -0.9996552 ]
 [ 0.8723992   1.         -0.99998736  0.9889294   0.99541616]]


In [10]:
print('Y1_val:{}\n{}'.format(Y1_val.shape, Y1_val))

Y1_val:(4, 5)
[[-0.9984713   0.9999982  -0.9920964   1.         -0.999999  ]
 [ 0.06534407 -0.9755484   0.48994452  1.         -0.9999934 ]
 [ 0.7172975   0.9999898  -0.92639166  1.         -1.        ]
 [ 0.24199198 -0.8737504  -0.99972963  0.9740634   0.8074469 ]]
